services:
  - type: web
    name: urlst-service
    runtime: node
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: shorturl
      - key: JWT_SECRET
        generateValue: true
      - key: BASE_URL
        sync: false
      - key: ANALYTICS_SERVICE_URL
        sync: false
